name: CI

on: [pull_request]
env:
  REPOSITORIES: |
    krogertechnology/kps-galaxy-irm
    krogertechnology/kps-galaxy-cd
    krogertechnology/kps-galaxy-procor
    krogertechnology/kps-galaxy-purhis
    krogertechnology/kps-galaxy-scription
    krogertechnology/kps-galaxy-uiitem
    krogertechnology/kps-galaxy-irrcor 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: ./
        with:
          TOKEN: '${{ secrets.GH_TOKEN }}'
          REPOSITORIES: '${{ env.REPOSITORIES }}'
